Attribute VB_Name = "z__NameSpaces"
' This file is generated by Zebra VBA Packager https://github.com/AutoActuary/zebra-vba-packager
Public Compress As New z__Compress__
Public CsvUtils As New z__CsvUtils__
Public Json As New z__Json__
Public StrUtils As New z__StrUtils__
Public VLib As New z__VLib__